<?php

return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'font_dir' => storage_path('fonts/'),
        'font_cache' => storage_path('app/pdf-fonts'),
        'temp_dir' => sys_get_temp_dir(),
        'chroot' => realpath(base_path()),
        'enable_font_subsetting' => true,
        'pdf_backend' => 'CPDF',
        'default_media_type' => 'screen',
        'default_paper_size' => 'a4',
        'default_font' => 'Times-Roman',
        'default_font_size' => 11,
        'dpi' => 96,
        'enable_php' => true,
        'enable_javascript' => true,
        'enable_remote' => true,
        'font_height_ratio' => 1.1,
        'enable_html5_parser' => true,
    ],
    'font_family' => [
        'serif' => ['Times-Roman', 'Times New Roman'],
        'sans-serif' => ['Helvetica', 'Arial'],
        'monospace' => ['Courier', 'Courier New'],
    ],
    'memory_limit' => env('DOMPDF_MEMORY_LIMIT', '512M'),
    'font_metrics_cache' => [
        'enabled' => true,
        'path' => storage_path('app/pdf-fonts/metrics'),
    ],
    'options' => [
        'enable_font_subsetting' => true,
        'enable_php' => false,
        'memory_limit' => env('DOMPDF_MEMORY_LIMIT', '512M'),
        'isHtml5ParserEnabled' => true,
        'debugPng' => false,
        'debugKeepTemp' => false,
        'debugCss' => false,
        'debugLayout' => false,
        'enable_remote' => false,
        'temp_dir' => storage_path('app/pdf-temp'),
        'font_cache' => storage_path('app/pdf-fonts'),
        'defaultFont' => 'Times-Roman',
        'fontCache' => storage_path('app/pdf-fonts'),
        'fontMetricsCache' => storage_path('app/pdf-fonts/metrics'),
        'fontDir' => storage_path('app/pdf-fonts'),
        'fontHeightRatio' => 0.9,
        'dpi' => 96,
        'isFontSubsettingEnabled' => true,
        'isRemoteEnabled' => false,
        'isJavascriptEnabled' => false,
        'isHtml5ParserEnabled' => true,
        'isPhpEnabled' => false,
        'pdfBackend' => 'CPDF',
        'defaultMediaType' => 'print',
    ],
];